---
title: 'Customising Your Models With TensorFlow 2'
output: html_document
---
<style type='text/css'>
pre:not([class]) {
    background-color: unset;
}
pre {
    border: none;
}
.container-fluid {
    padding: 0;
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = F, message = F, error = T, echo = T)
```

[Lab 01 Layer Nodes](#layer-nodes)  
[Lab 02 Device Placement](#device-placement)  
[Lab 03 The Keras Functional API](#the-keras-functional-api)  
[Lab 04 Keras TimeseriesGenerator](#keras-timeseriesgenerator)  
[Lab 05 Creating Datasets From Different Sources](#creating-datasets-from-different-sources)  
[Lab 06 TensorFlow Datasets](#tensorflow-datasets)  
[Lab 07 Data Pipeline](#data-pipeline)  
[Lab 08 Tokenising Text Data](#tokenising-text-data)  
[Lab 09 Stateful RNNs](#stateful-rnns)  
[Lab 10 Sequence Modelling](#sequence-modelling)  
[Lab 11 The Build Method](#the-build-method)  
[Lab 12 Tracking Metrics In Custom Training Loops](#tracking-metrics-in-custom-training-loops)  
[Lab 13 Model Subclassing And Custom Training Loops](#model-subclassing-and-custom-training-loops)  

### Layer Nodes

`r htmltools::includeHTML('Lab 01 Layer Nodes.html')`

### Device Placement

`r htmltools::includeHTML('Lab 02 Device Placement.html')`

### The Keras Functional API

`r htmltools::includeHTML('Lab 03 The Keras Functional API.html')`

### Keras TimeseriesGenerator

`r htmltools::includeHTML('Lab 04 Keras TimeseriesGenerator.html')`

###  Creating Datasets From Different Sources

`r htmltools::includeHTML('Lab 05 Creating Datasets From Different Sources.html')`

### TensorFlow Datasets

`r htmltools::includeHTML('Lab 06 TensorFlow Datasets.html')`

### Data Pipeline

`r htmltools::includeHTML('Lab 07 Data Pipeline.html')`

### Tokenising Text Data

`r htmltools::includeHTML('Lab 08 Tokenising Text Data.html')`

### Stateful RNNs

`r htmltools::includeHTML('Lab 09 Stateful RNNs.html')`

### Sequence Modelling

`r htmltools::includeHTML('Lab 10 Sequence Modelling.html')`

### The Build Method

`r htmltools::includeHTML('Lab 11 The Build Method.html')`

### Tracking Metrics In Custom Training Loops

`r htmltools::includeHTML('Lab 12 Tracking Metrics In Custom Training Loops.html')`

### Model Subclassing And Custom Training Loops

`r htmltools::includeHTML('Lab 13 Model Subclassing And Custom Training Loops.html')`
